# Generated by Django 5.0.7 on 2024-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_premierleaguegame_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premierleaguegame',
            options={'verbose_name': 'Premier League Game', 'verbose_name_plural': 'Premier League Games'},
        ),
    ]
