# Generated by Django 5.0.7 on 2024-11-04 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_premierleaguegame_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballmatch',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='match_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_time',
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='fixed_score',
            field=models.CharField(help_text='Format: X - Y (e.g., 2 - 0)', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Profit percentage', max_digits=5),
        ),
    ]
