# Generated by Django 5.0.7 on 2024-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_footballmatch_match_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='purchased_package_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
