# Generated by Django 5.0.7 on 2024-11-05 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_referralbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bethistory',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
