# Generated by Django 5.0.7 on 2024-11-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_soccer_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='leagues_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leagues_slider/')),
            ],
            options={
                'verbose_name': 'leagues_slider',
                'verbose_name_plural': 'leagues_slider',
            },
        ),
    ]
