# Generated by Django 5.0.7 on 2024-11-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_leagues_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
