# Generated by Django 5.0.7 on 2024-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_depositrequest_payment_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalTimeAndDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_date', models.DateField()),
                ('withdrawal_time', models.TimeField()),
            ],
        ),
    ]
