# Generated by Django 5.0.7 on 2024-11-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_footballmatch_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotgame',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('won', 'Won'), ('lost', 'Lost')], default='playing', max_length=10),
        ),
    ]
