# Generated by Django 5.0.7 on 2024-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_bethistory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasepackage',
            options={},
        ),
        migrations.AlterField(
            model_name='purchasepackage',
            name='weekly_withdrawal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='purchasepackage',
            unique_together={('user', 'name')},
        ),
    ]
