# Generated by Django 5.0.7 on 2024-11-23 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_prediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='referral',
        ),
        migrations.AddField(
            model_name='account',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
