# Generated by Django 5.0.7 on 2024-11-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_account_referral_account_referrals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='referrals',
            new_name='referral',
        ),
    ]
